# Dionysus
define voice_demo_fencing_dionysus_01 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_01.ogg"
define voice_demo_fencing_dionysus_02 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_02.ogg"
define voice_demo_fencing_dionysus_03 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_03.ogg"
define voice_demo_fencing_dionysus_04 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_04.ogg"
define voice_demo_fencing_dionysus_05 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_05.ogg"
define voice_demo_fencing_dionysus_06 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_06.ogg"
define voice_demo_fencing_dionysus_07 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_07.ogg"
define voice_demo_fencing_dionysus_08 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_08.ogg"
define voice_demo_fencing_dionysus_09 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_09.ogg"
define voice_demo_fencing_dionysus_10 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_10.ogg"
define voice_demo_fencing_dionysus_11 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_11.ogg"
define voice_demo_fencing_dionysus_12 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_12.ogg"
define voice_demo_fencing_dionysus_13 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_13.ogg"
define voice_demo_fencing_dionysus_14 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_14.ogg"
define voice_demo_fencing_dionysus_15 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_15.ogg"
define voice_demo_fencing_dionysus_16 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_16.ogg"
define voice_demo_fencing_dionysus_17 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_17.ogg"
define voice_demo_fencing_dionysus_18 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_18.ogg"
define voice_demo_fencing_dionysus_19 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_19.ogg"
define voice_demo_fencing_dionysus_20 = "assets/voice/Dionysus/dionysus_demo_fencing/demo_fencing_dionysus_20.ogg"

# Hephaestus
define voice_demo_fencing_hephaestus_01 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_01.ogg"
define voice_demo_fencing_hephaestus_02 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_02.ogg"
define voice_demo_fencing_hephaestus_03 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_03.ogg"
define voice_demo_fencing_hephaestus_04 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_04.ogg"
define voice_demo_fencing_hephaestus_05 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_05.ogg"
define voice_demo_fencing_hephaestus_06 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_06.ogg"
define voice_demo_fencing_hephaestus_07 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_07.ogg"
define voice_demo_fencing_hephaestus_08 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_08.ogg"
define voice_demo_fencing_hephaestus_09 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_09.ogg"
define voice_demo_fencing_hephaestus_10 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_10.ogg"
define voice_demo_fencing_hephaestus_11 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_11.ogg"
define voice_demo_fencing_hephaestus_12 = "assets/voice/Hephaestus/hephaestus_demo_fencing/demo_fencing_hephaestus_12.ogg"

# Nike
define voice_demo_fencing_nike_01 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_01.ogg"
define voice_demo_fencing_nike_02 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_02.ogg"
define voice_demo_fencing_nike_03 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_03.ogg"
define voice_demo_fencing_nike_04 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_04.ogg"
define voice_demo_fencing_nike_05 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_05.ogg"
define voice_demo_fencing_nike_06 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_06.ogg"
define voice_demo_fencing_nike_07 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_07.ogg"
define voice_demo_fencing_nike_08 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_08.ogg"
define voice_demo_fencing_nike_09 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_09.ogg"
define voice_demo_fencing_nike_10 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_10.ogg"
define voice_demo_fencing_nike_11 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_11.ogg"
define voice_demo_fencing_nike_12 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_12.ogg"
define voice_demo_fencing_nike_13 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_13.ogg"
define voice_demo_fencing_nike_14 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_14.ogg"
define voice_demo_fencing_nike_15 = "assets/voice/Nike/nike_demo_fencing/demo_fencing_nike_15.ogg"

# Zeus
define voice_demo_fencing_zeus_01 = "assets/voice/Zeus/zeus_demo_fencing/demo_fencing_zeus_01.ogg"
define voice_demo_fencing_zeus_02 = "assets/voice/Zeus/zeus_demo_fencing/demo_fencing_zeus_02.ogg"
define voice_demo_fencing_zeus_03 = "assets/voice/Zeus/zeus_demo_fencing/demo_fencing_zeus_03.ogg"
define voice_demo_fencing_zeus_04 = "assets/voice/Zeus/zeus_demo_fencing/demo_fencing_zeus_04.ogg"
define voice_demo_fencing_zeus_05 = "assets/voice/Zeus/zeus_demo_fencing/demo_fencing_zeus_05.ogg"
define voice_demo_fencing_zeus_06 = "assets/voice/Zeus/zeus_demo_fencing/demo_fencing_zeus_06.ogg"
define voice_demo_fencing_zeus_07 = "assets/voice/Zeus/zeus_demo_fencing/demo_fencing_zeus_07.ogg"
define voice_demo_fencing_zeus_08 = "assets/voice/Zeus/zeus_demo_fencing/demo_fencing_zeus_08.ogg"
define voice_demo_fencing_zeus_09 = "assets/voice/Zeus/zeus_demo_fencing/demo_fencing_zeus_09.ogg"